### PR TITLE
Update genericUrls.xml

### PR DESCRIPTION
**Pull request by yusha1439**
Changed video source for Dalmar TV to youtube, rtmp source no longer works

### CODE REVIEW

**Comment by skype007** [comment]
Are you sure rtmp source no longer works ? It worked with me
I don't know it it's the cause but your librtmp is updated ? (bit.ly/SCLibrtmp)

**Comment by yusha1439** [comment]
The owner has moved to using YouTube, as shown on his website.
www.dalmartv.com/live

**Comment by yusha1439** [comment]
Also, I just tested to make sure and it's not working, although other Rtmp
source is fine.

**Comment by yusha1439** [comment]
Can someone please merge this? Current channel in kodi is not working.

**Comment by Shani-08** [comment]
Thanks keep it up.

**Pull request merged**
