### PR TITLE
Update Channels.xml

### PR DESCRIPTION
**Pull request by Vision-85**
More logos size updates.

### CODE REVIEW

**Comment by Vision-85** [comment]
Someone could accept the changes? 
Thanks!

**Comment by hassuni** [comment]
@allouch89 can you please add vision-85

**Comment by allouch89** [comment]
Yes when i get back home

**Comment by allouch89** [comment]
Done. Thank you @Vision-85 for your good work.
You have been added as a collaborator so you can make changes your self without the need of others accepting it, just be extra careful for mistakes before submitting the changes.

**Comment by Vision-85** [comment]
Thank you @allouch89 & @hassuni for adding me to this project. I will be careful with the changes, even though I will mostly be working on updating the existing channel logs (resize & high-quality with compressed png).

**Pull request merged**
