### PR TITLE
Patch 4

### PR DESCRIPTION
**Pull request by ih26**

### CODE REVIEW

**Comment by Shani-08** [comment]
why are we moving Bein Movies 1,2 3???

**Comment by Shani-08** [comment]
also the channels.xml file is not completed its missing begining </channel></channels>
please fix the channels file

**Comment by ih26** [comment]
Sorry about that, had my files mixed up. Hopefully this is ok, I checked them.

**Comment by ih26** [comment]
added new teledunet channels

**Comment by Shani-08** [comment]
Many thanks ,looks great!

**Comment by Shani-08** [comment]
Please anything we rename or delete there could be URL files using those name. I don't mind renaming but make sure those URL files are updated with correct name.

**Comment by zombiB** [comment]
of course I updated the files available here 
livetvurl is not available can you replace it with this file http://pastebin.com/raw/5y9eNwpE
and can you replace this in glarab `<streaminginfo>
	<cname>Bein Sport</cname>
	<item>
	<title>Proxy HD</title>
	<link>http://$GLProxyIP$:4500/channel.flv?server=$GL-IPHD$&amp;channel=beINSports_HD&amp;port=2077&amp;user=$GL-User$&amp;session=$GL-Sesession$</link>
	</item>
</streaminginfo>` to `<streaminginfo>
	<cname>Bein Sport HD</cname>
	<item>
	<title>Proxy HD</title>
	<link>http://$GLProxyIP$:4500/channel.flv?server=$GL-IPHD$&amp;channel=beINSports_HD&amp;port=2077&amp;user=$GL-User$&amp;session=$GL-Sesession$</link>
	</item>
</streaminginfo>`
ttvurls and karurls are not used nomore
thank you

**Comment by Shani-08** [comment]
Livetv urls are here in livetvhdurls.xml

**Comment by Shani-08** [comment]
Also your link is not valid.

**Comment by Shani-08** [comment]
I meant the pastebin link

**Comment by zombiB** [comment]
awesome thank you :)

**Pull request merged**
